[project]
name = "mimic-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "paho-mqtt>=2.1.0",
    "pyqt6>=6.10.2",
    "pyqtgraph>=0.14.0",
    "pyyaml>=6.0.3",
    "qtpy>=2.4.3",
]
