broker: "broker.ip.adress"

devices:
  - id: "dummy_power_supply"
    name: "Dummy Power Supply"
    nickname: "DPS"
    device_cat: "Power Supply"
    mqtt_base_topic: "powersupply/serial_number"
    
    channels:
      - key: "voltage_ch1"
        label: "Voltage (Ch1)"
        description: "Output voltage for Channel 1"
        type: "float"
        access: "read_write"
        unit: "V"
        status_suffix: "voltage/1"   
        command_suffix: "SET/voltage/1" 

      - key: "current_ch1"
        label: "Current (Ch1)"
        description: "Output current for Channel 1"
        type: "float"
        access: "read_write"
        unit: "A"
        status_suffix: "current/1"
        command_suffix: "SET/current/1"

      - key: "output_state_ch1"
        label: "Output Enable"
        type: "boolean"
        access: "read_write"
        status_suffix: "output/1"
        command_suffix: "SET/output/1"
        
      - key: "voltage_ch2"
        label: "Voltage (Ch2)"
        description: "Output voltage for Channel 2"
        type: "float"
        access: "read_write"
        unit: "V"
        status_suffix: "voltage/2"   
        command_suffix: "SET/voltage/2" 

      - key: "current_ch2"
        label: "Current (Ch2)"
        description: "Output current for Channel 2"
        type: "float"
        access: "read_write"
        unit: "A"
        status_suffix: "current/2"
        command_suffix: "SET/current/2"

      - key: "output_state_ch2"
        label: "Output Enable"
        type: "boolean"
        access: "read_write"
        status_suffix: "output/2"
        command_suffix: "SET/output/2"
        

  - id: "dummy_sensor"
    name: "Dummy Sensor"
    nickname: "DS"
    device_cat: "Sensor"
    mqtt_base_topic: "Sensor/serial_number"
    
    channels:
      - key: "counts"
        label: "Counts"
        type: "integer"
        access: "read"
        status_suffix: "counts"
      
      - key: "signal"
        label: "Signal"
        type: "float"
        access: "read"
        status_suffix: "signal"


  - id: "dummy_shutter"
    name: "Dummy Shutter"
    nickname: "DShutter"
    device_cat: "Miscellaneous"
    mqtt_base_topic: "shutter/serial_number"

    channels:
      - key: "output_state"
        label: "Output"
        type: "boolean"
        access: "read_write"
        status_suffix: "out"
        command_suffix: "SET/out"

      - key: "pulse"
        label: "Pulse"
        type: "float"
        unit: "ms"
        access: "write"
        command_suffix: "SET/pulse"

  - id: "dummy_wavemeter"
    name: "Dummy Wavemeter"
    nickname: "DWM"
    device_cat: "Sensor"
    mqtt_base_topic: "DWM/serial_number"

    channels:
      - key: "chnl1"
        label: "Channel 1"
        type: "float"
        access: "read_write"
        unit: "THz"
        status_suffix: "frequency/1"
        command_suffix: "SET/frequency/1"

      - key: "chnl2"
        label: "Channel 2"
        type: "float"
        access: "read_write"
        unit: "THz"
        status_suffix: "frequency/2"
        command_suffix: "SET/frequency/2"

      - key: "chnl3"
        label: "Channel 3"
        type: "float"
        access: "read_write"
        unit: "THz"
        status_suffix: "frequency/3"
        command_suffix: "SET/frequency/3"

      - key: "chnl4"
        label: "Channel 4"
        type: "float"
        access: "read_write"
        unit: "THz"
        status_suffix: "frequency/4"
        command_suffix: "SET/frequency/4"
